name: Publish

on:
  push:
    tags: v*

env:
  NODE_VERSION: 14

jobs:
  test:
    name: Publish to Markeplace
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: node --version
      - run: npm --version

      - name: NPM Install
        run: |
          npm ci
          npm ls --depth=0

      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }
